name: cross_storage
description: JsInterop for zendesk/cross-storage
version: 1.0.1
homepage: https://github.com/moczix/dart_cross_storage
author: Moczniak <czornypan@gmail.com>

environment:
  sdk: ">=2.6.0-dev.7.0 <3.0.0"

dependencies:

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.6.3